In [1]:
%matplotlib inline
from matplotlib import pyplot as plt
from matplotlib import colors
import csv
import numpy as np
import pandas as pd
import cobra

In [2]:
cobra.__version__

'0.17.1'

In [3]:
Annotation = pd.read_excel('../../Data/R_toruloides_Data_for_Reconstruction.xlsx',
                          sheet_name='Annotation', index_col=0)
Annotation.index = Annotation.index.map(str)
Annotation = Annotation.fillna('')
Transcriptomics = pd.read_excel('../../Data/R_toruloides_Data_for_Reconstruction.xlsx',
                          sheet_name='Transcriptomics', header=[0,1,2,3], index_col=0)
Transcriptomics.index = Transcriptomics.index.map(str)
Proteomics = pd.read_excel('../../Data/R_toruloides_Data_for_Reconstruction.xlsx',
                          sheet_name='Proteomics', header=[0,1,2], index_col=0)
Proteomics.index = Proteomics.index.map(str)
Fitness = pd.read_excel('../../Data/R_toruloides_Data_for_Reconstruction.xlsx',
                          sheet_name='Fitness', index_col=0)
Fitness.index = Fitness.index.map(str)

In [4]:
def background_gradient(s, cmap='seismic', text_color_threshold=0.408):
    lim = max(abs(s.min().min()),abs(s.max().max()))
    rng = 2.0*lim
    norm = colors.Normalize(-lim - (rng * 0.2), lim + (rng * 0.2))
    rgbas = plt.cm.get_cmap(cmap)(norm(s.values))
    def relative_luminance(rgba):
        r, g, b = (x / 12.92 if x <= 0.03928 else ((x + 0.055) / 1.055 ** 2.4) for x in rgba[:3])
        return 0.2126 * r + 0.7152 * g + 0.0722 * b
    def css(rgba):
        dark = relative_luminance(rgba) < text_color_threshold
        text_color = '#f1f1f1' if dark else '#000000'
        return 'background-color: {b};color: {c};'.format(b=colors.rgb2hex(rgba), c=text_color)

    if s.ndim == 1:
        return [css(rgba) for rgba in rgbas]
    else:
        return pd.DataFrame([[css(rgba) for rgba in row] for row in rgbas], index=s.index, columns=s.columns)

def Show_Data(x):
    display(Transcriptomics.loc[x].style.background_gradient(cmap='Reds', low=0.2, high=0.2, axis=None))
    temp = [y for y in x if y in Proteomics.index]
    display(Proteomics.loc[temp].style.background_gradient(cmap='Reds', low=0.2, high=0.2, axis=None))
    temp = [y for y in x if y in Fitness.index]
    display(Fitness.loc[temp].style.apply(background_gradient, cmap='seismic', axis=None))
    return;

In [5]:
eco = cobra.io.load_json_model('../../Data/BiGG_Models/iML1515.json')
sce = cobra.io.load_json_model('../../Data/BiGG_Models/iMM904.json')
hsa = cobra.io.load_json_model('../../Data/BiGG_Models/RECON1.json')
hsa2 = cobra.io.load_json_model('../../Data/BiGG_Models/Recon3D.json')

In [6]:
model = cobra.io.load_json_model("IFO0880_GPR_1c.json")

In [7]:
print(len(model.genes))
print(len([x for x in model.genes if not x.id[0].isalpha()]))
model

1231
1154


<Model R. toruloides at 0x102d579748>

Glycolysis  
Glucose transport	
STL1	10704	plas 20, E.R. 3, mito 2, vacu 2		AQV*  
HXT2	11075	plas 21, E.R. 4	KOG0254: Predicted transporter (major facilitator superfamily)	EDV*  
GAL2	11893	plas 25	K08139: HXT; MFS transporter, SP family, sugar:H+ symporter	EVH*  
Hexokinase (D-glucose:ATP)	
GLK1	10264	cyto 10, cyto_mito 8.333, cyto_nucl 6.833, mito 5.5, pero 4, cysk 3, nucl 2.5	K00844: HK; hexokinase	VTK*  
HXK2	11982	mito 20, cyto 4, pero 2	K00844: HK; hexokinase	AHV*  
Glucose-6-phosphate isomerase  
PGI1	9589	cyto 14, pero 10, vacu 2	K01810: GPI, pgi; glucose-6-phosphate isomerase	SRA*  
Phosphofructokinase  
PFK1	8859	cyto 21, pero 3, mito 2	K00850: pfkA, PFK; 6-phosphofructokinase 1	QTS*  
PFK2	8863	nucl 11, cyto_nucl 10.5, cyto 8, pero 4, mito 3	K00850: pfkA, PFK; 6-phosphofructokinase 1	QTS*  
PFK3	8867	cyto 16, mito 8, cyto_nucl 8		QTS*  
Fructose-bisphosphatase  
FBP1	15423	cyto 17.5, cyto_nucl 15.5, nucl 6.5		KDQ*  
Fructose-bisphosphate aldolase  
FBA1	15420	cyto 15.5, cyto_mito 11.666, cyto_nucl 10.833, mito 6.5, nucl 4		GTL*  
Triose-phosphate isomerase  
TPI1	9300	mito 17, cyto 6, pero 4	K01803: TPI, tpiA; triosephosphate isomerase (TIM)	AKL*  
Glyceraldehyde-3-phosphate dehydrogenase  
TDH1	10613	cyto 27	K00134: GAPDH, gapA; glyceraldehyde 3-phosphate dehydrogenase	GKL*  
Phosphoglycerate kinase  
PGK1	15721	cyto 13.5, mito 12, cyto_nucl 7.5	K00927: PGK, pgk; phosphoglycerate kinase	EKQ*  
Phosphoglycerate mutase  
GPM1	9910	mito 16, cyto 8, nucl 2	K01834: PGAM, gpmA; 2,3-bisphosphoglycerate-dependent phosphoglycerate mutase	ESK*  
GPM2	12393	mito 15.5, cyto_mito 11.666, cyto_nucl 6.833, cyto 6.5, nucl 5	K15634: gpmB; probable phosphoglycerate mutase	GAQ*  
GPM3	11229	nucl 19.5, cyto_nucl 13, cyto 5.5	KOG4754: Predicted phosphoglycerate mutase	RTY*  
GPM4?	15425	mito 19, nucl 5, cyto 3	K15634: gpmB; probable phosphoglycerate mutase	AQI*  
Enolase  
ENO1	9037	mito 19.5, cyto_mito 14, cyto 7.5	K01689: ENO, eno; enolase	SRK*

In [8]:
temp = ['10704','11075','11893','10264','11982','9589','8859','8863','8867','11513','15423','15195','15744',
        '15420','9300','10613','15721','9910','11229','12393','12637','15425','9037']
Annotation.loc[temp]

Combined Annotations Signal P  \
RTO4_ID                                                               
10704    KOG0254: Predicted transporter (major facilita...        S   
11075    KOG0254: Predicted transporter (major facilita...            
11893    K08139: HXT; MFS transporter, SP family, sugar...        S   
10264                               K00844: HK; hexokinase            
11982                               K00844: HK; hexokinase            
9589       K01810: GPI, pgi; glucose-6-phosphate isomerase            
8859            K00850: pfkA, PFK; 6-phosphofructokinase 1            
8863            K00850: pfkA, PFK; 6-phosphofructokinase 1            
8867            K00850: pfkA, PFK; 6-phosphofructokinase 1            
11513    HMMPfam:haloacid dehalogenase-like hydrolase:P...            
15423      K03841: FBP, fbp; fructose-1,6-bisphosphatase I            
15195    K19029: PFKFB2; 6-phosphofructo-2-kinase / fru...            
15744    K19030: PFKFB4; 6-phosphofructo-2-kinase / fru...        S   
15420    K01624: FBA, fbaA; fructose-bisphosphate aldol...            
9300     K01803: TPI, tpiA; triosephosphate isomerase (...            
10613    K00134: GAPDH, gapA; glyceraldehyde 3-phosphat...            
15721            K00927: PGK, pgk; phosphoglycerate kinase            
9910     K01834: PGAM, gpmA; 2,3-bisphosphoglycerate-de...            
11229           KOG4754: Predicted phosphoglycerate mutase            
12393       K15634: gpmB; probable phosphoglycerate mutase            
12637       K15634: gpmB; probable phosphoglycerate mutase            
15425       K15634: gpmB; probable phosphoglycerate mutase            
9037                             K01689: ENO, eno; enolase            

                                          Sc288c Orthologs  \
RTO4_ID                                                      
10704                                                 STL1   
11075    YDL245C,YDR342C,YDR343C,HXT3,YEL069C,HXT10,HXT...   
11893    YDL245C,YDR342C,YDR343C,HXT3,YEL069C,HXT10,HXT...   
10264                                  GLK1,EMI2,HXK1,HXK2   
11982                                  GLK1,EMI2,HXK1,HXK2   
9589                                                  PGI1   
8859                                             PFK1,PFK2   
8863                                             PFK1,PFK2   
8867                                             PFK1,PFK2   
11513                                                        
15423                                                 FBP1   
15195                                                FBP26   
15744                                              YLR345W   
15420                                                 FBA1   
9300                                                  TPI1   
10613                                       TDH3,TDH1,TDH2   
15721                                                 PGK1   
9910                                                  GPM1   
11229                                                        
12393                                                        
12637                                                SHB17   
15425                                              YOR283W   
9037                        ENO1,ENO2,ERR3,YOR393W,YPL281C   

                     Human Orthologs Sc288 Best Hit Human Blast  \
RTO4_ID                                                           
10704                                          STL1       SLC2A   
11075                                          GAL2       SLC2A   
11893                                          HXT7       SLC2A   
10264              HK1,HK2,HK3,HKDC1           HXK2         HK1   
11982              HK1,HK2,HK3,HKDC1           HXK2        HK2e   
9589                             GPI           PGI1         GPI   
8859                  PFKL,PFKM,PFKP           PFK2        PFKL   
8863                  PFKL,PFKM,PFKP           PFK2        PFKL   
8867                  PFKL,PFKM,PFKP     

In [9]:
for x in temp:
    if x in model.genes:
        for r in sorted(model.genes.get_by_id(x).reactions, key=lambda x: x.id):
            print(r.id, r.reaction, r.gene_reaction_rule)
    else:
        print(x, 'no reactions')
    print()

GALt2 gal_e + h_e --> gal_c + h_c 10704 or 11075 or 11893 or (10704 and 11075) or (10704 and 11893)
GLCt1 glc__D_e --> glc__D_c 10452 or 10704 or 11075 or 11893 or 15762 or 9102 or 9841
GLUt2r glu__L_e + h_e <=> glu__L_c + h_c 10704 or 14229 or 15074 or 8962 or 9319 or 9322 or 9962 or (YALI0E20713g and 10704 and 14229 and 8962) or (YALI0E20713g and 10704 and 14229 and 9319) or (YALI0E20713g and 10704 and 14229 and 9322) or (YALI0E20713g and 10704 and 14229 and 9962) or (YALI0E20713g and 10704 and 15074 and 8962) or (YALI0E20713g and 10704 and 15074 and 9319) or (YALI0E20713g and 10704 and 15074 and 9322) or (YALI0E20713g and 10704 and 15074 and 9962)

FRUt2 fru_e + h_e --> fru_c + h_c 11075 or 11893
GALt2 gal_e + h_e --> gal_c + h_c 10704 or 11075 or 11893 or (10704 and 11075) or (10704 and 11893)
GLCt1 glc__D_e --> glc__D_c 10452 or 10704 or 11075 or 11893 or 15762 or 9102 or 9841
MANt2 h_e + man_e --> h_c + man_c 11075 or 11893

FRUt2 fru_e + h_e --> fru_c + h_c 11075 or 11893
GALt2 

In [10]:
# 10704 STL1 glycerol proton symporter of plasma membrane
# 10704 and 10705 gene models wrong, they are one gene
# GLYCt2 has 12792 GUP1/GUP2, which is O-acyltransferase involved in remodeling of the GPI anchor
model.reactions.get_by_id('GLYCt2').gene_reaction_rule = '10704 and 10705'
model.reactions.get_by_id('GALt2').gene_reaction_rule = '11075 or 11893'
model.reactions.get_by_id('GLCt1').gene_reaction_rule = '10452 or 11075 or 11893 or 15762 or 9102 or 9841'
model.reactions.get_by_id('GLUt2r').gene_reaction_rule = '14229 or 15074 or 8962 or 9319 or 9322 or 9962'
model.remove_reactions(['GALth','XYLt2pp','ABFPTh','AM6PTh','GLUKAh','GLUKBh'], remove_orphans=True)

In [11]:
# 11513 is putative phosphatase - ycsE in B. subtilis, 5-amino-6-(5-phospho-D-ribitylamino)uracil phosphatase
# Blast of known E. coli and B. subtilis genes hit to 11513
# PMDPHT is needed for riboflavin biosynthesis
r = sce.reactions.get_by_id('PMDPHT').copy()
model.add_reactions([r])
model.reactions.get_by_id('PMDPHT').gene_reaction_rule = '11513'
# Remove 11513 from other reactions
model.reactions.get_by_id('F1PP').gene_reaction_rule = '14546 or 8576'
model.reactions.get_by_id('F6PP').gene_reaction_rule = '14546 or 8576'
model.reactions.get_by_id('FBP').gene_reaction_rule = '15423'
model.reactions.get_by_id('G1PP').gene_reaction_rule = '8576'
model.reactions.get_by_id('MN6PP').gene_reaction_rule = '8460'
model.reactions.get_by_id('R5PP').gene_reaction_rule = '13044 or 14546 or 8576'
# 15195 or 15744 are Fructose-6-phosphate 2-kinase/fructose-2,6-biphosphatase -> FBP26 and PFK26
model.reactions.get_by_id('FBP26').gene_reaction_rule = '15195 or 15744'
model.remove_reactions(['BFBPh','RZ5PP','TPIh','PGKh'], remove_orphans=True)
# 9910 PGAM1, 12393 PGAM2, 11229 predicted phosphoglycerate mutase, 15425 broad substrate specificity phosphatase
# 12637 is sedoheptulose bisphosphatase
r = model.reactions.get_by_id('FBP26').copy()
r.id = 'SBP'
r.name = 'Sedoheptulose-bisphosphatase'
r.subsystem = 'Calvin cycle/Pentose phosphate pathway'
r.gene_reaction_rule = '12637'
model.add_reactions([r])
r.add_metabolites({'f26bp_c': 1.0, 'f6p_c': -1.0, 's17bp_c': -1.0, 's7p_c': 1.0})
# Remove 12637 from PGM
model.reactions.get_by_id('PGM').gene_reaction_rule = '11229 or 12393 or 15425 or 9910'
model.remove_reactions(['PGMf','PGMm','ENOf','ENOm'], remove_orphans=True)

Pentose phosphate pathway  
Glucose 6-phosphate dehydrogenase	
ZWF1	10000	K00036: G6PD, zwf; glucose-6-phosphate 1-dehydrogenase	cyto_nucl 13.5, nucl 12.5, cyto 11.5	SVL*  
6-phosphogluconolactonase	
SOL1	14499	K01057: PGLS, pgl, devB; 6-phosphogluconolactonase	cyto_nucl 10.833, cyto 10.5, nucl 7, cyto_mito 6.832, pero 5, extr 2	SKL*  
SOL2	14132	K07404: pgl; 6-phosphogluconolactonase	cyto 13, cyto_mito 10.833, cyto_nucl 9.333, mito 7.5, nucl 4.5	WLP*  
Phosphogluconate dehydrogenase	
GND1	15167	K00033: PGD, gnd, gntZ; 6-phosphogluconate dehydrogenase	cyto 21, cysk 4	YNV*  
GND2	10592	KOG2653: 6-phosphogluconate dehydrogenase
Ribulose 5-phosphate 3-epimerase	
RPE1	16264	K01783: rpe, RPE; ribulose-phosphate 3-epimerase	cyto 19, extr 4, nucl 2, mito 2, mito_nucl 2	EGL*  
Ribose-5-phosphate isomerase	
RKI1	13288	K01807: rpiA; ribose 5-phosphate isomerase A	mito 21, cyto 6	QRV*  
Transketolase	
TKL1	15631	K00615: E2.2.1.1, tktA, tktB; transketolase	cyto 20, cyto_nucl 12, pero 4	IHA*  
Transaldolase	
TAL1	10173	K00616: E2.2.1.2, talA, talB; transaldolase	cyto 20, cyto_nucl 13, nucl 4	KLQ*  
Pyruvate kinase	
CDC19	13002	K00873: PK, pyk; pyruvate kinase	cyto 15.5, cyto_nucl 9.833, cyto_pero 9.166, cysk 6, nucl 2, mito 2	PVE*  
Pyruvate decarboxylase	
PDC1	15791	K01568: PDC, pdc; pyruvate decarboxylase	cyto 21.5, cyto_mito 11.5, nucl 3	NAA*  
Aldehyde dehydrogenase	
ALDH	12042	K00128: ALDH; aldehyde dehydrogenase (NAD+)	cyto 18.5, cyto_nucl 10, mito 4, pero 4	NPL*  
Acetyl-CoA synthetase	
ACS2	14597	K01895: ACSS, acs; acetyl-CoA synthetase	cyto 13, plas 5, mito 3, pero 2, mito_nucl 2	SSE*  
ACS1	15276	K01907: AACS, acsA; acetoacetyl-CoA synthetase	plas 9, pero 6, mito 5, cyto 5, cyto_mito 5	SKL*  
Butanediol dehydrogenase	
BDH1	13641	K00004: BDH, butB; (R,R)-butanediol dehydrogenase / meso-butanediol dehydrogenase / diacetyl reductase	plas 11, cyto 8.5, cyto_nucl 5, mito 3, E.R. 2	QPF*  
BDH2	9634	K00004: BDH, butB; (R,R)-butanediol dehydrogenase / meso-butanediol dehydrogenase / diacetyl reductase	cyto 16, mito 7, nucl 2	EEK*  
Pyruvate carboxylase	
PYC2	16630	K01958: PC, pyc; pyruvate carboxylase	mito 19, cyto 7	VHS*  
Phosphoenolpyruvate carboxykinase	
PCK1	10841	K01610: E4.1.1.49, pckA; phosphoenolpyruvate carboxykinase (ATP)	mito 17.5, cyto_mito 12, cyto 5.5, pero 3	PKI*

In [12]:
temp = ['10000','14499','14132','15167','10592','16264','13288','15631','10173','13002','15791','12042','14597',
        '12272','15276','13641','9634','16630','10841']
display(Annotation.loc[temp])
Show_Data(temp)

Combined Annotations Signal P  \
RTO4_ID                                                               
10000    K00036: G6PD, zwf; glucose-6-phosphate 1-dehyd...            
14499    K01057: PGLS, pgl, devB; 6-phosphogluconolacto...            
14132               K07404: pgl; 6-phosphogluconolactonase            
15167    K00033: PGD, gnd, gntZ; 6-phosphogluconate deh...            
10592            KOG2653: 6-phosphogluconate dehydrogenase            
16264     K01783: rpe, RPE; ribulose-phosphate 3-epimerase            
13288         K01807: rpiA; ribose 5-phosphate isomerase A            
15631          K00615: E2.2.1.1, tktA, tktB; transketolase            
10173          K00616: E2.2.1.2, talA, talB; transaldolase            
13002                     K00873: PK, pyk; pyruvate kinase            
15791             K01568: PDC, pdc; pyruvate decarboxylase            
12042          K00128: ALDH; aldehyde dehydrogenase (NAD+)            
14597             K01895: ACSS, acs; acetyl-CoA synthetase            
12272                         KOG1176: Acyl-CoA synthetase            
15276       K01907: AACS, acsA; acetoacetyl-CoA synthetase            
13641    K00004: BDH, butB; (R,R)-butanediol dehydrogen...            
9634     K00004: BDH, butB; (R,R)-butanediol dehydrogen...            
16630                K01958: PC, pyc; pyruvate carboxylase            
10841    K01610: E4.1.1.49, pckA; phosphoenolpyruvate c...        S   

                 Sc288c Orthologs                        Human Orthologs  \
RTO4_ID                                                                    
10000                        ZWF1                                   G6PD   
14499              SOL1,SOL3,SOL2                                   PGLS   
14132                                                                      
15167                   GND2,GND1                                    PGD   
10592                                                                      
16264                        RPE1                              RPE,RPEL1   
13288                        RKI1                                   RPIA   
15631                   TKL2,TKL1                        TKT,TKTL1,TKTL2   
10173                   TAL1,NQM1                                 TALDO1   
13002                  CDC19,PYK2                               PKLR,PKM   
15791         THI3,PDC6,PDC1,PDC5                                          
12042    ALD5,ALD4,ALD6,ALD3,ALD2  ALDH1A1,ALDH1A2,ALDH1A3,ALDH1B1,ALDH2   
14597                   ACS1,ACS2                            ACSS1,ACSS2   
12272                                                                      
15276                                                               AACS   
13641                YAL061W,BDH1                                          
9634                 YAL061W,BDH1                                          
16630                   PYC2,PYC1                                     PC   
10841                        PCK1                                          

        Sc288 Best Hit Human Blast      Essential  \
RTO4_ID                                             
10000             ZWF1        G6PD      Essential   
14499             SOL1        PGLS      Essential   
14132                               Not Essential   
15167             GND1         PGD      Essential   
10592             GND2         PGD  Not Essential   
16264             RPE1         RPE      Essential   
13288             RKI1        RPIA      Essential   
15631             TKL1         TKT      Essential   
10173             TAL1       TALDO      Essential   
13002            CDC19         PKM      Essential   
15791             PDC1              Not Essential   
12042             ALD5       ALDH2  Not Essential   
14597             ACS2       ACSS1  Not Essential   
12272                               Not Essential   
15276             ACS1        AACS  Not Essential   
13641             BDH1        SORD  Not Essentia

In [13]:
for x in temp:
    if x in model.genes:
        for r in sorted(model.genes.get_by_id(x).reactions, key=lambda x: x.id):
            print(r.id, r.reaction, r.gene_reaction_rule)
    else:
        print(x, 'no reactions')
    print()

G6PDH2r g6p_c + nadp_c <=> 6pgl_c + h_c + nadph_c 10000

PGL 6pgl_c + h2o_c --> 6pgc_c + h_c 14132 or 14499
PGLh 6pgl_h + h2o_h --> 6pgc_h + h_h 14499

PGL 6pgl_c + h2o_c --> 6pgc_c + h_c 14132 or 14499

GND 6pgc_c + nadp_c --> co2_c + nadph_c + ru5p__D_c 15167
PGDHh 6pgc_h + nadp_h --> co2_h + nadph_h + ru5p__D_h 15167
yli_R1379 6pgc_c + nad_c --> co2_c + nadh_c + ru5p__D_c 15167

10592 no reactions

RPE ru5p__D_c <=> xu5p__D_c 16264
RPEh ru5p__D_h <=> xu5p__D_h 16264

RPI r5p_c <=> ru5p__D_c 13288
RPIh r5p_h <=> ru5p__D_h 13288
yli_R0482 yli_M00116_c <=> ru5p__D_c 13288

TKT1 r5p_c + xu5p__D_c <=> g3p_c + s7p_c 15631
TKT1h r5p_h + xu5p__D_h <=> g3p_h + s7p_h 15631
TKT2 e4p_c + xu5p__D_c <=> f6p_c + g3p_c 15631
TKT2h e4p_h + xu5p__D_h <=> f6p_B_h + g3p_h 15631
yli_R0485 g3p_c + s7p_c <=> xu5p__D_c + yli_M00116_c 15631

TALA g3p_c + s7p_c <=> e4p_c + f6p_c 10173
TAh g3p_h + s7p_h <=> e4p_h + f6p_B_h 10173

AGPOP dgdp_c + h_c + pep_c --> dgtp_c + pyr_c 13002
AGPOPm dgdp_m + 2.0 h_m + pe

Dual localization of oxidative PP pathway in cyto and pero  
https://academic.oup.com/femsyr/article/12/1/61/642733  
PYK1 in yeast has no entries in brenda for other cofactors than ADP  
PYRDC2 is lumped reaction of PYRDC and ACALDCD  
OAADC is a sub-reaction of malate dehydrogenase  

In [14]:
r = model.reactions.get_by_id('G6PDH2r').copy()
r.id = 'G6PDH2rp'
model.add_reactions([r])
for m in r.metabolites:
    if not m.id.replace('_c','_x') in model.metabolites:
        m2 = m.copy()
        m2.id = m.id.replace('_c','_x')
        m2.compartment = 'x'
        model.add_metabolites([m2])
    r.add_metabolites({m.id: -r.get_coefficient(m.id), m.id.replace('_c','_x'): r.get_coefficient(m.id)})

model.reactions.get_by_id('PGL').gene_reaction_rule = '14132'
r = model.reactions.get_by_id('PGL').copy()
r.id = 'PGLp'
r.gene_reaction_rule = '14499'
model.add_reactions([r])
for m in r.metabolites:
    if not m.id.replace('_c','_x') in model.metabolites:
        m2 = m.copy()
        m2.id = m.id.replace('_c','_x')
        m2.compartment = 'x'
        model.add_metabolites([m2])
    r.add_metabolites({m.id: -r.get_coefficient(m.id), m.id.replace('_c','_x'): r.get_coefficient(m.id)})

r = model.reactions.get_by_id('GND').copy()
r.id = 'GNDp'
r.gene_reaction_rule = '10592'
model.add_reactions([r])
for m in r.metabolites:
    if not m.id.replace('_c','_x') in model.metabolites:
        m2 = m.copy()
        m2.id = m.id.replace('_c','_x')
        m2.compartment = 'x'
        model.add_metabolites([m2])
    r.add_metabolites({m.id: -r.get_coefficient(m.id), m.id.replace('_c','_x'): r.get_coefficient(m.id)})
remove = ['PGLh','PGDHh','yli_R1379','RPEh','RPIh','yli_R0482','TKT1h','TKT2h','yli_R0485','TAh','AGPOP','AGPOPm',
          'DAPOP','GTPOPm','PYK3','PYKf','PYKm','yli_R1553','yli_R1554','yli_R1557','PYRDC2','PCm','PPCKm']
model.remove_reactions(remove, remove_orphans=True)

In [15]:
temp = ['12761','13917','11178','10614']
display(Annotation.loc[temp])
Show_Data(temp)

Combined Annotations Signal P  \
RTO4_ID                                                               
12761    K00029: E1.1.1.40, maeB; malate dehydrogenase ...            
13917    K00027: ME2, sfcA, maeA; malate dehydrogenase ...        S   
11178                   K00026: MDH2; malate dehydrogenase            
10614                   K00026: MDH2; malate dehydrogenase            

        Sc288c Orthologs Human Orthologs Sc288 Best Hit Human Blast  \
RTO4_ID                                                               
12761               MAE1     ME1,ME2,ME3           MAE1        ME1e   
13917               MAE1     ME1,ME2,ME3           MAE1        ME1e   
11178               MDH1            MDH2           MDH1        MDH2   
10614                                              MDH1        MDH2   

             Essential                                          WolfPSort  \
RTO4_ID                                                                     
12761    Not Essential  mito 8, cyto 7.5, cyto_nucl 7.5, nucl 6.5, pero 4   
13917    Not Essential                   mito 18, cyto 6.5, cyto_nucl 4.5   
11178        Essential                                            mito 27   
10614    Not Essential                       cyto 14, mito 7, cyto_nucl 7   

        C Terminal  
RTO4_ID             
12761         QAQ*  
13917         DRH*  
11178         MSA*  
10614         PKL*

In [16]:
for x in temp:
    for r in sorted(model.genes.get_by_id(x).reactions, key=lambda x: x.id):
        print(r.id, r.reaction, r.gene_reaction_rule)
    print()

MDHC_nadp_hr mal__L_h + nadp_h <=> co2_h + nadph_h + pyr_h 12761
ME1 mal__L_c + nad_c --> co2_c + nadh_c + pyr_c 12761 or 13917
ME1m mal__L_m + nad_m --> co2_m + nadh_m + pyr_m 12761 or 13917
ME2 mal__L_c + nadp_c --> co2_c + nadph_c + pyr_c 12761 or 13917
ME2m mal__L_m + nadp_m --> co2_m + nadph_m + pyr_m 12761 or 13917

ME1 mal__L_c + nad_c --> co2_c + nadh_c + pyr_c 12761 or 13917
ME1m mal__L_m + nad_m --> co2_m + nadh_m + pyr_m 12761 or 13917
ME2 mal__L_c + nadp_c --> co2_c + nadph_c + pyr_c 12761 or 13917
ME2m mal__L_m + nadp_m --> co2_m + nadph_m + pyr_m 12761 or 13917

MDH mal__L_c + nad_c <=> h_c + nadh_c + oaa_c 10614 or 11178
MDHf h_f + nadh_f + oaa_f <=> mal__L_f + nad_f 10614 or 11178
MDHh h_h + nadh_h + oaa_h <=> mal__L_h + nad_h 10614 or 11178
MDHm mal__L_m + nad_m <=> h_m + nadh_m + oaa_m 10614 or 11178
MDHp mal__L_x + nad_x <=> h_x + nadh_x + oaa_x 10614 or 11178
SLDxm nad_m + sl__L_m <=> 3spyr_m + h_m + nadh_m 11178
yli_R1494 nad_c + yli_M07013_c --> h_c + nadh_c + yli

In [17]:
# 12671 ME1/maeB 1.1.1.40 cyto NADP, and 13917 ME2/maeA 1.1.1.38 mito NAD
model.reactions.get_by_id('OAADC').gene_reaction_rule = '12761'
r = model.reactions.get_by_id('OAADC').copy()
r.id = 'OAADCm'
r.name = 'Oxaloacetate decarboxylase mitochondrial'
r.gene_reaction_rule = '13917'
model.add_reactions([r])
for m in r.metabolites:
    if not m.id.replace('_c','_m') in model.metabolites:
        m2 = m.copy()
        m2.id = m.id.replace('_c','_m')
        m2.compartment = 'm'
        model.add_metabolites([m2])
    r.add_metabolites({m.id: -r.get_coefficient(m.id), m.id.replace('_c','_m'): r.get_coefficient(m.id)})
model.reactions.get_by_id('ME2').gene_reaction_rule = '12761'
model.reactions.get_by_id('ME1m').gene_reaction_rule = '13917'
model.remove_reactions(['MDHC_nadp_hr','ME1','ME2m'], remove_orphans=True)
# 11178 MDH1 yeast / MDH2 human 1.1.1.37 mito, 10614 weak sigP and PKL* -> MDH3 yeast?
model.reactions.get_by_id('MDHm').gene_reaction_rule = '11178'
model.reactions.get_by_id('MDHp').gene_reaction_rule = '10614'
model.remove_reactions(['MDH','MDHf','MDHh','SLDxm','yli_R1494'], remove_orphans=True)

Pyruvate metabolism and the TCA cycle  
Pyruvate transport in via proton symport	
JEN1	10184	K08178: JEN; MFS transporter, SHS family, lactate transporter	plas 25	SAY*  
Pyruvate dehydrogenase mitochondrial	
LPD1	10040	K00382: DLD, lpd, pdhD; dihydrolipoamide dehydrogenase	mito 9, cyto 8, extr 7, pero 2	INA*  
PDA1	13630	K00161: PDHA, pdhA; pyruvate dehydrogenase E1 component alpha subunit	mito 25.5, cyto_mito 13.5	STV*  
PDX1	13722	KOG0557: Dihydrolipoamide acetyltransferase	mito 23.5, cyto_mito 12.833, cyto_nucl 1.833	LGL*  
PDB1	13948	K00162: PDHB, pdhB; pyruvate dehydrogenase E1 component beta subunit	cysk 14, cyto 7, cyto_nucl 5.5, mito 4	YRV*  
LAT1	14126	K00627: DLAT, aceF, pdhC; pyruvate dehydrogenase E2 component (dihydrolipoamide acetyltransferase)	cyto 24.5, cyto_nucl 13.333	FML*  
Citrate synthase	
CIT1	11331	K01647: CS, gltA; citrate synthase	mito 26.5, cyto_mito 14	LVK*  
CIT2	8548	K01647: CS, gltA; citrate synthase	cyto 12, cyto_nucl 8, mito 5, pero 4, cysk 4	SKL*  
Citrate transport mitochondrial	
CTP1	10514	K15100: SLC25A1, CTP; solute carrier family 25 (mitochondrial citrate transporter), member 1	extr 13, mito 5, E.R. 3, vacu 3, cyto_mito 3	RAV*  
Aconitate hydratase	
ACO1	11624	K01681: ACO, acnA; aconitate hydratase	mito 18.5, cyto_mito 13, cyto 6.5	SKQ*  
ACO2	14600	K17450: ACO2; homoaconitase	mito 20, cyto 4.5, cyto_nucl 3.5	GQA*  

In [18]:
temp = ['10184','10040','13630','13722','13948','14126','11331','8548','10514','11624','14600']
display(Annotation.loc[temp])
Show_Data(temp)

Combined Annotations Signal P  \
RTO4_ID                                                               
10184    K08178: JEN; MFS transporter, SHS family, lact...            
10040    K00382: DLD, lpd, pdhD; dihydrolipoamide dehyd...        S   
13630    K00161: PDHA, pdhA; pyruvate dehydrogenase E1 ...            
13722          KOG0557: Dihydrolipoamide acetyltransferase            
13948    K00162: PDHB, pdhB; pyruvate dehydrogenase E1 ...            
14126    K00627: DLAT, aceF, pdhC; pyruvate dehydrogena...            
11331                   K01647: CS, gltA; citrate synthase            
8548                    K01647: CS, gltA; citrate synthase            
10514    K15100: SLC25A1, CTP; solute carrier family 25...        S   
11624               K01681: ACO, acnA; aconitate hydratase            
14600                          K17450: ACO2; homoaconitase            

        Sc288c Orthologs  Human Orthologs Sc288 Best Hit Human Blast  \
RTO4_ID                                                                
10184               JEN1                            JEN1               
10040               LPD1              DLD           LPD1         DLD   
13630               PDA1      PDHA1,PDHA2           PDA1       PDHA2   
13722               PDX1                            PDX1        PDHX   
13948               PDB1             PDHB           PDB1        PDHB   
14126               LAT1             DLAT           LAT1        DLAT   
11331     CIT2,CIT1,CIT3               CS           CIT1         CSe   
8548                                HDDC3           CIT1               
10514               CTP1          SLC25A1           CTP1      SLC25A   
11624          ACO2,ACO1  ACO1,IREB2,ACO2           ACO1        ACO2   
14600          ACO2,ACO1  ACO1,IREB2,ACO2           ACO2        ACO2   

             Essential                                     WolfPSort  \
RTO4_ID                                                                
10184    Not Essential                                       plas 25   
10040        Essential                mito 9, cyto 8, extr 7, pero 2   
13630        Essential                     mito 25.5, cyto_mito 13.5   
13722    Not Essential  mito 23.5, cyto_mito 12.833, cyto_nucl 1.833   
13948        Essential        cysk 14, cyto 7, cyto_nucl 5.5, mito 4   
14126        Essential                   cyto 24.5, cyto_nucl 13.333   
11331        Essential                       mito 26.5, cyto_mito 14   
8548     Not Essential  cyto 12, cyto_nucl 8, mito 5, pero 4, cysk 4   
10514    Not Essential  extr 13, mito 5, E.R. 3, vacu 3, cyto_mito 3   
11624    Not Essential             mito 18.5, cyto_mito 13, cyto 6.5   
14600    Not Essential              mito 20, cyto 4.5, cyto_nucl 3.5   

        C Terminal  
RTO4_ID             
10184         SAY*  
10040         INA*  
13630         STV*  
13722         LGL*  
13948         YRV*  
14126         FML*  
11331         LVK*  
8548          SKL*  
10514         RAV*  
11624         SKQ*  
14600         GQA*

In [19]:
for x in temp:
    for r in sorted(model.genes.get_by_id(x).reactions, key=lambda x: x.id):
        print(r.id, r.reaction, r.gene_reaction_rule)
    print()

ACNAMt2pp acnam_p + h_p --> acnam_c + h_c 10184
D_LACt2 h_e + lac__D_e <=> h_c + lac__D_c 10184
L_LACt2r h_e + lac__L_e <=> h_c + lac__L_c 10184
PYRt2 h_e + pyr_e --> h_c + pyr_c 10184

2OXOADOXm 2oxoadp_m + coa_m + nad_m --> co2_m + glutcoa_m + nadh_m 10040 and 12116 and 9274
AKGDm akg_m + coa_m + nad_m --> co2_m + nadh_m + succoa_m 10007 and 10040 and 12116
GLYCLm gly_m + nad_m + thf_m --> co2_m + mlthf_m + nadh_m + nh4_m 10040 and 10205 and 12898 and 15184
OBDHm 2obut_m + coa_m + nad_m --> co2_m + nadh_m + ppcoa_m (10040 and 11183 and 12566 and 15436) or (10040 and 11188 and 12566 and 15436)
OIVD1m 4mop_m + coa_m + nad_m --> co2_m + ivcoa_m + nadh_m (10040 and 11183 and 12566 and 15436) or (10040 and 11188 and 12566 and 15436)
OIVD2m 3mob_m + coa_m + nad_m --> co2_m + ibcoa_m + nadh_m (10040 and 11183 and 12566 and 15436) or (10040 and 11188 and 12566 and 15436)
OIVD3m 3mop_m + coa_m + nad_m --> 2mbcoa_m + co2_m + nadh_m (10040 and 11183 and 12566 and 15436) or (10040 and 11188 and 

In [20]:
temp = ['11328','12642','16016']
display(Annotation.loc[temp])

Combined Annotations Signal P Sc288c Orthologs  \
RTO4_ID                                                                        
11328                    KOG2617: Citrate synthase        S                    
12642    K01720: prpD; 2-methylcitrate dehydratase        S             PDH1   
16016        K01705: LYS4; homoaconitate hydratase                      LYS4   

        Human Orthologs Sc288 Best Hit Human Blast      Essential  \
RTO4_ID                                                             
11328                             CIT3         CSe  Not Essential   
12642                             PDH1              Not Essential   
16016                             LYS4        ACO2  Not Essential   

                                                 WolfPSort C Terminal  
RTO4_ID                                                                
11328    extr 10, mito 7, cyto 3.5, cyto_nucl 3, pero 3...       GLPI  
12642                                              mito 26       HKP*  
16016                                      mito 23, cyto 4       ISA*

In [21]:
model.remove_reactions(['ACNAMt2pp'], remove_orphans=True)
# 11331 CIT1 mito, 8548 CIT2 pero, 11328 CIT3 mito 2-methylcitrate
model.reactions.get_by_id('CSm').gene_reaction_rule = '11331'
model.reactions.get_by_id('CSp').gene_reaction_rule = '8548'
model.reactions.get_by_id('MCITSm').gene_reaction_rule = '11328'
model.remove_reactions(['CS'], remove_orphans=True)
# 11624 ACO1 mito citrate
model.reactions.get_by_id('ACN_a_m').id = 'ACONTam'
model.reactions.get_by_id('ACN_b_m').id = 'ACONTbm'
model.reactions.get_by_id('ACONTam').gene_reaction_rule = '11624'
model.reactions.get_by_id('ACONTbm').gene_reaction_rule = '11624'
model.remove_reactions(['ACONT','ACONTa','ACONTb','ACONTm'], remove_orphans=True)
# 14600 ACO2 mito homocitrate (first half)
# 16016 LYS4 homoaconitate hydratase (second half)
# Change b124tc to hacon_C
r = sce.reactions.get_by_id('MCITDm').copy()
r.id = 'HACONTam'
r.name = 'Homocitrate hydrolase mitochondrial'
r.gene_reaction_rule = '14600'
model.add_reactions([r])
model.reactions.get_by_id('HACNHm').id = 'HACONTbm'
model.metabolites.get_by_id('b124tc_m').id = 'hacon_C_m'
model.metabolites.get_by_id('hacon_C_m').name = 'Cis-Homoaconitate'
model.remove_reactions(['yli_R0417'], remove_orphans=True)
# 12642 PDH1 mito 2-methylcitrate dehydratase
# ACONT3m is correct, remove MCITD and MICITDr
model.remove_reactions(['MCITD','MICITDr'], remove_orphans=True)

Rest of the TCA cycle  
Isocitrate dehydrogenase 	
IDH2	11681	K00030: IDH3; isocitrate dehydrogenase (NAD+)	mito 26	KKL*  
IDH1	11682	K00030: IDH3; isocitrate dehydrogenase (NAD+)	mito 24.5, cyto_mito 13.5	GLQ*  
IDP1	11129	K00031: IDH1, IDH2, icd; isocitrate dehydrogenase	cyto 13, pero 8, nucl 4	PKL*  
Oxoglutarate dehydrogenase mitochondrial 	
KGD1	10007	K00164: OGDH, sucA; 2-oxoglutarate dehydrogenase E1 component	mito 25	GDF*  
KGD2	12116	K00658: DLST, sucB; 2-oxoglutarate dehydrogenase E2 component (dihydrolipoamide succinyltransferase)	mito 23, cyto_mito 14.5	LYN*  
Glycine cleavage complex  mitochondrial	
GCV1	12898	K00605: gcvT, AMT; aminomethyltransferase	mito 23, cyto 4	RGE*  
GCV2	10205	K00281: GLDC, gcvP; glycine dehydrogenase	mito 21, cyto 2, plas 1, extr 1, cyto_nucl 1, pero 1, E.R. 1	VDA*  
GCV3	15184	K02437: gcvH, GCSH; glycine cleavage system H protein	mito 27	EAS*  
Succinate CoA ligase mitochondrial 	
LSC2	15967	K01900: LSC2; succinyl-CoA synthetase beta subunit	mito 18.5, cyto_mito 12.5, cyto 5.5	AAQ*  
LSC1	16144	K01899: LSC1; succinyl-CoA synthetase alpha subunit	mito 24, pero 2	GLA*  
Succinate dehydrogenase mitochondrial 	
SDH1	16281	K00234: SDHA, SDH1; succinate dehydrogenase (ubiquinone) flavoprotein subunit	mito 27	VRG*  
SDH2	11977	K00235: SDHB, SDH2; succinate dehydrogenase (ubiquinone) iron-sulfur subunit	nucl 9, mito 7, cyto 7, cyto_mito 7	ASA*  
SHH3	11629	K00236: SDHC, SDH3; succinate dehydrogenase (ubiquinone) cytochrome b560 subunit	mito 22.5, cyto_mito 13.5, cyto 3.5	LAM*  
SHH4	11802	K00237: SDHD, SDH4; succinate dehydrogenase (ubiquinone) membrane anchor subunit	mito 10, extr 8, cyto_mito 8	KQE*  
Succinate fumarate transport mitochondrial	
SFC1	12605	K15100: SLC25A1, CTP; solute carrier family 25 (mitochondrial citrate transporter), member 1	mito 11, cyto 9.5, cyto_nucl 5.5, plas 3	YSE*  
UCP2	11740	K15103: UCP2_3, SLC25A8_9; solute carrier family 25 (mitochondrial uncoupling protein), member 8/9	mito 15, cysk 6, cyto 4.5, cyto_nucl 3	PPV*  
DIC1	13510	K13577: SLC25A10, DIC; solute carrier family 25 (mitochondrial dicarboxylate transporter), member 10	mito 15, extr 7, cyto 3	GTP*  
Fumarate reductase	
FRD1	11420	KOG2404: Fumarate reductase, flavoprotein subunit	cyto 16.5, cyto_nucl 9, extr 8	YKQ*  
Fumarase	
FUM1	14001	K01679: E4.2.1.2B, fumC; fumarate hydratase, class II	cyto 17, cyto_nucl 14, nucl 7	SDA*  
Oxaloacetate transport mitochondrial	
OAC1	9011	K15117: SLC25A34_35, OAC1; solute carrier family 25, member 34/35	extr 14, mito 11	ARD*  
Isocitrate lyase	
ICL1	14022	K01637: E4.1.3.1, aceA; isocitrate lyase	cyto_nucl 9.5, cyto 8.5, nucl 7.5, pero 7, mito 2	QFK*  
ICL2	14162	K01637: E4.1.3.1, aceA; isocitrate lyase	mito 26	HTF*  
Malate synthase	
MLS1	9457	K01638: aceB, glcB; malate synthase	cyto_pero 12, cyto 11.5, pero 11.5, nucl 3	AKL*  
Phosphate transporter mitochondrial	
MIR1	15874	K15102: SLC25A3, PHC, PIC; solute carrier family 25 (mitochondrial phosphate transporter), member 3	mito 12, extr 7, cyto 5.5, cyto_nucl 3.5	HKD*  
ATP-Citrate lyase	
ACLY	9726	K01648: ACLY; ATP citrate (pro-S)-lyase	cyto 13.5, mito 8, cyto_nucl 7.5, extr 2, pero 2	QRQ*

In [22]:
temp = ['11681','11682','11129','10007','12116','10040','12898','10205','15184','15967','16144','16281',
        '11977','11629','11802','12605','11740','13510','11420','11536','14001','9011','14022','14162','9457',
        '15874','9726']
display(Annotation.loc[temp])
Show_Data(temp)

Combined Annotations Signal P  \
RTO4_ID                                                               
11681        K00030: IDH3; isocitrate dehydrogenase (NAD+)            
11682        K00030: IDH3; isocitrate dehydrogenase (NAD+)            
11129    K00031: IDH1, IDH2, icd; isocitrate dehydrogenase            
10007    K00164: OGDH, sucA; 2-oxoglutarate dehydrogena...        S   
12116    K00658: DLST, sucB; 2-oxoglutarate dehydrogena...            
10040    K00382: DLD, lpd, pdhD; dihydrolipoamide dehyd...        S   
12898            K00605: gcvT, AMT; aminomethyltransferase            
10205            K00281: GLDC, gcvP; glycine dehydrogenase            
15184    K02437: gcvH, GCSH; glycine cleavage system H ...            
15967    K01900: LSC2; succinyl-CoA synthetase beta sub...            
16144    K01899: LSC1; succinyl-CoA synthetase alpha su...            
16281    K00234: SDHA, SDH1; succinate dehydrogenase (u...            
11977    K00235: SDHB, SDH2; succinate dehydrogenase (u...            
11629    K00236: SDHC, SDH3; succinate dehydrogenase (u...        A   
11802    K00237: SDHD, SDH4; succinate dehydrogenase (u...        S   
12605    K15100: SLC25A1, CTP; solute carrier family 25...        S   
11740    K15103: UCP2_3, SLC25A8_9; solute carrier fami...            
13510    K13577: SLC25A10, DIC; solute carrier family 2...            
11420    KOG2404: Fumarate reductase, flavoprotein subunit        S   
11536    KOG2404: Fumarate reductase, flavoprotein subunit            
14001    K01679: E4.2.1.2B, fumC; fumarate hydratase, c...            
9011     K15117: SLC25A34_35, OAC1; solute carrier fami...        S   
14022             K01637: E4.1.3.1, aceA; isocitrate lyase            
14162             K01637: E4.1.3.1, aceA; isocitrate lyase        S   
9457                   K01638: aceB, glcB; malate synthase            
15874    K15102: SLC25A3, PHC, PIC; solute carrier fami...            
9726               K01648: ACLY; ATP citrate (pro-S)-lyase            

        Sc288c Orthologs          Human Orthologs Sc288 Best Hit Human Blast  \
RTO4_ID                                                                        
11681               IDH2                    IDH3A           IDH2       IDH3A   
11682               IDH1              IDH3B,IDH3G           IDH1       IDH3G   
11129     IDP1,IDP2,IDP3                IDH1,IDH2           IDP1        IDH2   
10007               KGD1        DHTKD1,OGDH,OGDHL           KGD1        OGDH   
12116               KGD2                     DLST           KGD2        DLST   
10040               LPD1                      DLD           LPD1         DLD   
12898               GCV1         AMT,RP11-949J7.8           GCV1         AMT   
10205               GCV2                     GLDC           GCV2        GLDC   
15184               GCV3                     GCSH           GCV3        GCSH   
15967               LSC2                   SUCLA2           LSC2       SUCLA   
16144               LSC1                   SUCLG1           LSC1       SUCLG   
16281       YJL045W,SDH1                     SDHA           SDH1        SDHA   
11977               SDH2                     SDHB           SDH2        SDHB   
11629       YMR118C,SDH3                     SDHC           SHH3               
11802    SDH4,SHH4,TIM18                                    SHH4               
12605               SFC1                                    SFC1      SLC25A   
11740                                        UCP2           OAC1       SLC25   
13510               DIC1  SLC25A11,RP13-1032I1.10           DIC1       SLC25   
11420          FRD1,OSM1                                    FRD1       CYB5B   
11536                                                       FRD1               
14001               FUM1                       FH           FUM1        FHes   
9011                OAC1                 SLC25A35           OAC1       SLC25   
14022          ICL1,ICL2                                  

In [23]:
for x in temp:
    for r in sorted(model.genes.get_by_id(x).reactions, key=lambda x: x.id):
        print(r.id, r.reaction, r.gene_reaction_rule)
    print()

ICDHxm icit_m + nad_m --> akg_m + co2_m + nadh_m 11681 or 11682 or (11681 and 11682)
ICDHyr icit_c + nadp_c <=> akg_c + co2_c + nadph_c 11129 or 11681

ICDHxm icit_m + nad_m --> akg_m + co2_m + nadh_m 11681 or 11682 or (11681 and 11682)

ICDHym icit_m + nadp_m --> akg_m + co2_m + nadph_m 11129
ICDHyp icit_x + nadp_x --> akg_x + co2_x + nadph_x 11129
ICDHyr icit_c + nadp_c <=> akg_c + co2_c + nadph_c 11129 or 11681

AKGDm akg_m + coa_m + nad_m --> co2_m + nadh_m + succoa_m 10007 and 10040 and 12116

2OXOADOXm 2oxoadp_m + coa_m + nad_m --> co2_m + glutcoa_m + nadh_m 10040 and 12116 and 9274
AKGDm akg_m + coa_m + nad_m --> co2_m + nadh_m + succoa_m 10007 and 10040 and 12116

2OXOADOXm 2oxoadp_m + coa_m + nad_m --> co2_m + glutcoa_m + nadh_m 10040 and 12116 and 9274
AKGDm akg_m + coa_m + nad_m --> co2_m + nadh_m + succoa_m 10007 and 10040 and 12116
GLYCLm gly_m + nad_m + thf_m --> co2_m + mlthf_m + nadh_m + nh4_m 10040 and 10205 and 12898 and 15184
OBDHm 2obut_m + coa_m + nad_m --> co2_m +

Isocitrate dehydrogenase http://emboj.embopress.org/content/17/3/677  
11681 IDH2 mito nadh alpha subunit  
11682 IDH1 mito nadh gamma subunit  
11129 IDP1/IDP2/IDP3 cyto 13 pero 8 nadph  
A. nidulans three isoforms http://www.jbc.org/content/276/40/37722  
y. lipolytica one isoform https://link.springer.com/article/10.1007%2Fs12010-013-0373-1  
Gene structure shows three isoforms possible  
RNA-Seq shows the slicing of short N-terminal (no MTS) and long C-terminal (PTS1)  
Change ICDHxm genes to '11681 and 11682', ICDHyp genes to '11129'  
Remove ICDHyr, ICDHym

Fumarate reductase  
11420 has sigP and cytochrome b5-like domain. In S. cer, mito Osm1 localizes to mitochondrial intermembrane space  
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5638582/pdf/2773.pdf  
11536 has cytochrome b5-like domain but FRD domain is ~50% coverage, located at the end of scaffold 16, essential  
These two look like the same sequence incorrectly assembled  
S. cer FRD1 and OSM1 do not have C-terminal cytochrome b5-like domain. Osm1 facilitates the transfer of electrons from Erv1 to fumarate, osm1 and erv1 are synthetic lethal in anaerobic conditions in S. cer  
16224 K17783: ERV1, GFER, ALR; mitochondrial FAD-linked sulfhydryl oxidase  
http://www.ebi.ac.uk/interpro/entry/IPR010960/proteins-matched?ida=392051  

In [24]:
model.reactions.get_by_id('ICDHxm').gene_reaction_rule = '11681 and 11682'
model.reactions.get_by_id('ICDHyp').gene_reaction_rule = '11129'
model.remove_reactions(['ICDHyr','ICDHym'], remove_orphans=True)
model.reactions.get_by_id('FRDcm').gene_reaction_rule = '11420 or 11536'
model.remove_reactions(['FRDm','FUM'], remove_orphans=True)

In [25]:
print(len(model.genes))
print(len(model.reactions))
print(len(model.metabolites))
model

1234
2351
2551


<Model R. toruloides at 0x102d579748>

In [26]:
for x in sorted(model.genes, key=lambda x: x.id):
    if not x.reactions:
        print(x)
print()
for x in sorted(model.metabolites, key=lambda x: x.id):
    if not x.reactions:
        print(x)

In [27]:
cobra.manipulation.remove_genes(model, [x for x in model.genes if not x.reactions])
model.remove_metabolites([x for x in model.metabolites if not x.reactions])

In [28]:
print(len(model.genes))
print(len(model.reactions))
print(len(model.metabolites))
model

1234
2351
2551


<Model R. toruloides at 0x102d579748>

In [29]:
for x in sorted(model.genes, key=lambda x: x.id):
    if not x.reactions:
        print(x)
print()
for x in sorted(model.metabolites, key=lambda x: x.id):
    if not x.reactions:
        print(x)

In [30]:
cobra.io.save_json_model(model, "IFO0880_GPR_1d.json")

In [31]:
model_old = cobra.io.load_json_model("IFO0880_GPR_1c.json")
model_new = cobra.io.load_json_model("IFO0880_GPR_1d.json")

In [32]:
print('Removed reactions\n')
for r in sorted(model_old.reactions, key=lambda x: x.id):
    if r not in model_new.reactions:
        print(r)

Removed reactions

ABFPTh: atp_h + fru_B_h --> adp_h + f6p_B_h + h_h
ACNAMt2pp: acnam_p + h_p --> acnam_c + h_c
ACN_a_m: acon_C_m + h2o_m <=> cit_m
ACN_b_m: acon_C_m + h2o_m <=> icit_m
ACONT: cit_c <=> icit_c
ACONTa: cit_c <=> acon_C_c + h2o_c
ACONTb: acon_C_c + h2o_c <=> icit_c
ACONTm: cit_m <=> icit_m
AGPOP: dgdp_c + h_c + pep_c --> dgtp_c + pyr_c
AGPOPm: dgdp_m + 2.0 h_m + pep_m --> dgtp_m + pyr_m
AM6PTh: atp_h + man_h --> adp_h + h_h + man6p_h
BFBPh: fdp_B_h + h2o_h --> f6p_B_h + pi_h
CS: accoa_c + h2o_c + oaa_c --> cit_c + coa_c + h_c
DAPOP: dadp_m + h_m + pep_m --> datp_m + pyr_m
ENOf: 2pg_f <=> h2o_f + pep_f
ENOm: 2pg_m <=> h2o_m + pep_m
FRDm: fadh2_m + fum_m --> fad_m + succ_m
FUM: fum_c + h2o_c <=> mal__L_c
GALth: gal_c + h_c <=> gal_h + h_h
GLUKAh: Glc_aD_h + atp_h --> adp_h + g6p_A_h + h_h
GLUKBh: atp_h + glc__bD_h --> adp_h + g6p_B_h + h_h
GTPOPm: gdp_m + 2.0 h_m + pep_m --> gtp_m + pyr_m
HACNHm: b124tc_m + h2o_m <=> hicit_m
ICDHym: icit_m + nadp_m --> akg_m + co2_m + nadph

In [33]:
print('Updated reactions\n')
for r in sorted(model_old.reactions, key=lambda x: x.id):
    if r in model_new.reactions:
        r2 = model_new.reactions.get_by_id(r.id)
        if (r.name == r2.name and r.reaction == r2.reaction and r.gene_reaction_rule == r2.gene_reaction_rule and
            r.lower_bound == r2.lower_bound and r.upper_bound == r2.upper_bound):
            pass
        else:
            print('Old', r, r.gene_reaction_rule)
            print('New', r2, r2.gene_reaction_rule)
            print()

Updated reactions

Old CSp: accoa_x + h2o_x + oaa_x --> cit_x + coa_x + h_x 11331 or 8548
New CSp: accoa_x + h2o_x + oaa_x --> cit_x + coa_x + h_x 8548

Old F1PP: f1p_c + h2o_c --> fru_c + pi_c 11513 or 14546 or 8576
New F1PP: f1p_c + h2o_c --> fru_c + pi_c 14546 or 8576

Old F6PP: f6p_c + h2o_c --> fru_c + pi_c 11513 or 14546 or 8576
New F6PP: f6p_c + h2o_c --> fru_c + pi_c 14546 or 8576

Old FBP: fdp_c + h2o_c --> f6p_c + pi_c 11513 or 15423
New FBP: fdp_c + h2o_c --> f6p_c + pi_c 15423

Old FBP26: f26bp_c + h2o_c --> f6p_c + pi_c 15195 or 15423 or 15744
New FBP26: f26bp_c + h2o_c --> f6p_c + pi_c 15195 or 15744

Old FRDcm: fadh2_m + fum_c --> fad_m + succ_c 11420
New FRDcm: fadh2_m + fum_c --> fad_m + succ_c 11420 or 11536

Old G1PP: g1p_c + h2o_c --> glc__D_c + pi_c 11513 or 8576
New G1PP: g1p_c + h2o_c --> glc__D_c + pi_c 8576

Old GALt2: gal_e + h_e --> gal_c + h_c 10704 or 11075 or 11893 or (10704 and 11075) or (10704 and 11893)
New GALt2: gal_e + h_e --> gal_c + h_c 11075 or 11

In [34]:
print('Added reactions\n')
for r in sorted(model_new.reactions, key=lambda x: x.id):
    if r not in model_old.reactions:
        print(r)

Added reactions

ACONTam: acon_C_m + h2o_m <=> cit_m
ACONTbm: acon_C_m + h2o_m <=> icit_m
G6PDH2rp: g6p_x + nadp_x <=> 6pgl_x + h_x + nadph_x
GNDp: 6pgc_x + nadp_x --> co2_x + nadph_x + ru5p__D_x
HACONTam: hcit_m <=> h2o_m + hacon_C_m
HACONTbm: h2o_m + hacon_C_m <=> hicit_m
OAADCm: h_m + oaa_m --> co2_m + pyr_m
PGLp: 6pgl_x + h2o_x --> 6pgc_x + h_x
PMDPHT: 5aprbu_c + h2o_c --> 4r5au_c + pi_c
SBP: h2o_c + s17bp_c --> pi_c + s7p_c
